name       : ruby-unf
version    : 0.1.4
release    : 3
source     :
    - https://rubygems.org/downloads/unf-0.1.4.gem : 4999517a531f2a955750f8831941891f6158498ec9b6cb1c81ce89388e63022e
license    : BSD-2-Clause
component  : programming.ruby
summary    : RubyGem - unf
description: |
    This is a wrapper library to bring Unicode Normalization Form support to Ruby/JRuby.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby-unf_ext
install    : |
    %gem_install
